### ISSUE TITLE
Remove unnecessary packages

### ISSUE THREAD

**Issue by pratikbin** [jim380/Cendermint#2]
Hello @jim380 Thanks for amazing project,

Just wanted to know is there any reason to install python?

https://github.com/jim380/Cendermint/blob/7f6a87c5a8621123eb62ad0b7f79fd111744064d/Dockerfile#L5

**Comment by jim380** [comment]
@pratikbin Not that I know of. I believe I took that from an older Dockerfile from one of my past projects.

**Comment by pratikbin** [comment]
Okay.. Let me do PR

**Comment by pratikbin** [comment]
https://github.com/jim380/Cendermint/pull/3
